/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 17.0.0.17000604) */

module pipe_demo(clk, rst_n, a_0 , a_1 , a_2 , a_3 , a_4 , a_5 , a_6 , a_7 , b_0 , b_1 , b_2 , b_3 , b_4 , b_5 , b_6 , b_7 , sel, y_0 , y_1 
, y_2 , y_3 , y_4 , y_5 , y_6 , y_7 );
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input a_0 ;
  wire a_0 ;
  input a_1 ;
  wire a_1 ;
  input a_2 ;
  wire a_2 ;
  input a_3 ;
  wire a_3 ;
  input a_4 ;
  wire a_4 ;
  input a_5 ;
  wire a_5 ;
  input a_6 ;
  wire a_6 ;
  input a_7 ;
  wire a_7 ;
  input b_0 ;
  wire b_0 ;
  input b_1 ;
  wire b_1 ;
  input b_2 ;
  wire b_2 ;
  input b_3 ;
  wire b_3 ;
  input b_4 ;
  wire b_4 ;
  input b_5 ;
  wire b_5 ;
  input b_6 ;
  wire b_6 ;
  input b_7 ;
  wire b_7 ;
  input sel;
  wire sel;
  output y_0 ;
  wire y_0 ;
  output y_1 ;
  wire y_1 ;
  output y_2 ;
  wire y_2 ;
  output y_3 ;
  wire y_3 ;
  output y_4 ;
  wire y_4 ;
  output y_5 ;
  wire y_5 ;
  output y_6 ;
  wire y_6 ;
  output y_7 ;
  wire y_7 ;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire s1_and_0 ;
  wire s1_and_1 ;
  wire s1_and_2 ;
  wire s1_and_3 ;
  wire s1_and_4 ;
  wire s1_and_5 ;
  wire s1_and_6 ;
  wire s1_and_7 ;
  wire s1_sum_0 ;
  wire s1_sum_1 ;
  wire s1_sum_2 ;
  wire s1_sum_3 ;
  wire s1_sum_4 ;
  wire s1_sum_5 ;
  wire s1_sum_6 ;
  wire s1_sum_7 ;
  wire s1_xor_1 ;
  wire s1_xor_2 ;
  wire s1_xor_3 ;
  wire s1_xor_4 ;
  wire s1_xor_5 ;
  wire s1_xor_6 ;
  wire s1_xor_7 ;
  wire s2_mix_0 ;
  wire s2_mix_1 ;
  wire s2_mix_2 ;
  wire s2_mix_3 ;
  wire s2_mix_4 ;
  wire s2_mix_5 ;
  wire s2_mix_6 ;
  wire s2_mix_7 ;
  sky130_fd_sc_hd__clkinv_1 _075_ (
    .A(s2_mix_6 ),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _076_ (
    .A(s2_mix_5 ),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _077_ (
    .A(s2_mix_4 ),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _078_ (
    .A(s2_mix_3 ),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _079_ (
    .A(s2_mix_2 ),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _080_ (
    .A(s2_mix_1 ),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _081_ (
    .A(s2_mix_0 ),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _082_ (
    .A(s1_xor_6 ),
    .Y(_047_)
  );
  sky130_fd_sc_hd__clkinv_1 _083_ (
    .A(s1_xor_5 ),
    .Y(_048_)
  );
  sky130_fd_sc_hd__clkinv_1 _084_ (
    .A(s1_xor_4 ),
    .Y(_049_)
  );
  sky130_fd_sc_hd__clkinv_1 _085_ (
    .A(s1_xor_3 ),
    .Y(_050_)
  );
  sky130_fd_sc_hd__clkinv_1 _086_ (
    .A(s1_xor_2 ),
    .Y(_051_)
  );
  sky130_fd_sc_hd__clkinv_1 _087_ (
    .A(s1_xor_1 ),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _088_ (
    .A(s2_mix_7 ),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _089_ (
    .A(s1_xor_7 ),
    .Y(_017_)
  );
  sky130_fd_sc_hd__and2_0 _090_ (
    .A(a_4 ),
    .B(b_4 ),
    .X(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _091_ (
    .A(a_4 ),
    .B(b_4 ),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nor2_1 _092_ (
    .A(_071_),
    .B(_018_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__and2_0 _093_ (
    .A(a_2 ),
    .B(b_2 ),
    .X(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _094_ (
    .A(a_2 ),
    .B(b_2 ),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor2_1 _095_ (
    .A(_069_),
    .B(_019_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__and2_0 _096_ (
    .A(a_7 ),
    .B(b_7 ),
    .X(_074_)
  );
  sky130_fd_sc_hd__and2_0 _097_ (
    .A(a_3 ),
    .B(b_3 ),
    .X(_070_)
  );
  sky130_fd_sc_hd__nor2_1 _098_ (
    .A(a_3 ),
    .B(b_3 ),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nor2_1 _099_ (
    .A(_070_),
    .B(_020_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__and2_0 _100_ (
    .A(a_5 ),
    .B(b_5 ),
    .X(_072_)
  );
  sky130_fd_sc_hd__nor2_1 _101_ (
    .A(a_5 ),
    .B(b_5 ),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor2_1 _102_ (
    .A(_072_),
    .B(_021_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor2_1 _103_ (
    .A(a_7 ),
    .B(b_7 ),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor2_1 _104_ (
    .A(_074_),
    .B(_022_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__and2_0 _105_ (
    .A(a_6 ),
    .B(b_6 ),
    .X(_073_)
  );
  sky130_fd_sc_hd__and2_0 _106_ (
    .A(a_1 ),
    .B(b_1 ),
    .X(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _107_ (
    .A(a_0 ),
    .B(b_0 ),
    .Y(_023_)
  );
  sky130_fd_sc_hd__clkinv_1 _108_ (
    .A(_023_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__xor2_1 _109_ (
    .A(a_1 ),
    .B(b_1 ),
    .X(_054_)
  );
  sky130_fd_sc_hd__a31o_1 _110_ (
    .A1(a_0 ),
    .A2(b_0 ),
    .A3(_054_),
    .B1(_068_),
    .X(_024_)
  );
  sky130_fd_sc_hd__a21o_1 _111_ (
    .A1(_055_),
    .A2(_024_),
    .B1(_069_),
    .X(_025_)
  );
  sky130_fd_sc_hd__a21o_1 _112_ (
    .A1(_056_),
    .A2(_025_),
    .B1(_070_),
    .X(_026_)
  );
  sky130_fd_sc_hd__a21o_1 _113_ (
    .A1(_057_),
    .A2(_026_),
    .B1(_071_),
    .X(_027_)
  );
  sky130_fd_sc_hd__a21o_1 _114_ (
    .A1(_058_),
    .A2(_027_),
    .B1(_072_),
    .X(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _115_ (
    .A(a_6 ),
    .B(b_6 ),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor2_1 _116_ (
    .A(_073_),
    .B(_029_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__a21oi_1 _117_ (
    .A1(_028_),
    .A2(_059_),
    .B1(_073_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _118_ (
    .A(_060_),
    .B(_030_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__xor2_1 _119_ (
    .A(_028_),
    .B(_059_),
    .X(_066_)
  );
  sky130_fd_sc_hd__xor2_1 _120_ (
    .A(_058_),
    .B(_027_),
    .X(_065_)
  );
  sky130_fd_sc_hd__xor2_1 _121_ (
    .A(_057_),
    .B(_026_),
    .X(_064_)
  );
  sky130_fd_sc_hd__xor2_1 _122_ (
    .A(_056_),
    .B(_025_),
    .X(_063_)
  );
  sky130_fd_sc_hd__xor2_1 _123_ (
    .A(_055_),
    .B(_024_),
    .X(_062_)
  );
  sky130_fd_sc_hd__xnor2_1 _124_ (
    .A(_023_),
    .B(_054_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _125_ (
    .A(sel),
    .B(s1_and_6 ),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xor2_1 _126_ (
    .A(s1_sum_6 ),
    .B(_031_),
    .X(_032_)
  );
  sky130_fd_sc_hd__o21ai_0 _127_ (
    .A1(sel),
    .A2(_047_),
    .B1(_032_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _128_ (
    .A(sel),
    .B(s1_and_5 ),
    .Y(_033_)
  );
  sky130_fd_sc_hd__xor2_1 _129_ (
    .A(s1_sum_5 ),
    .B(_033_),
    .X(_034_)
  );
  sky130_fd_sc_hd__o21ai_0 _130_ (
    .A1(sel),
    .A2(_048_),
    .B1(_034_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _131_ (
    .A(sel),
    .B(s1_and_4 ),
    .Y(_035_)
  );
  sky130_fd_sc_hd__xor2_1 _132_ (
    .A(s1_sum_4 ),
    .B(_035_),
    .X(_036_)
  );
  sky130_fd_sc_hd__o21ai_0 _133_ (
    .A1(sel),
    .A2(_049_),
    .B1(_036_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _134_ (
    .A(sel),
    .B(s1_and_3 ),
    .Y(_037_)
  );
  sky130_fd_sc_hd__xor2_1 _135_ (
    .A(s1_sum_3 ),
    .B(_037_),
    .X(_038_)
  );
  sky130_fd_sc_hd__o21ai_0 _136_ (
    .A1(sel),
    .A2(_050_),
    .B1(_038_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _137_ (
    .A(sel),
    .B(s1_and_2 ),
    .Y(_039_)
  );
  sky130_fd_sc_hd__xor2_1 _138_ (
    .A(s1_sum_2 ),
    .B(_039_),
    .X(_040_)
  );
  sky130_fd_sc_hd__o21ai_0 _139_ (
    .A1(sel),
    .A2(_051_),
    .B1(_040_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _140_ (
    .A(sel),
    .B(s1_and_1 ),
    .Y(_041_)
  );
  sky130_fd_sc_hd__xor2_1 _141_ (
    .A(s1_sum_1 ),
    .B(_041_),
    .X(_042_)
  );
  sky130_fd_sc_hd__o21ai_0 _142_ (
    .A1(sel),
    .A2(_016_),
    .B1(_042_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _143_ (
    .A(sel),
    .B(s1_and_0 ),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xnor2_1 _144_ (
    .A(s1_sum_0 ),
    .B(_043_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _145_ (
    .A(a_0 ),
    .B(b_0 ),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor2_1 _146_ (
    .A(_052_),
    .B(_044_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _147_ (
    .A(sel),
    .B(s1_and_7 ),
    .Y(_045_)
  );
  sky130_fd_sc_hd__xor2_1 _148_ (
    .A(s1_sum_7 ),
    .B(_045_),
    .X(_046_)
  );
  sky130_fd_sc_hd__o21ai_0 _149_ (
    .A1(sel),
    .A2(_017_),
    .B1(_046_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__dfrtp_1 _150_ (
    .CLK(clk),
    .D(_008_),
    .Q(y_0 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _151_ (
    .CLK(clk),
    .D(_009_),
    .Q(y_1 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _152_ (
    .CLK(clk),
    .D(_010_),
    .Q(y_2 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _153_ (
    .CLK(clk),
    .D(_011_),
    .Q(y_3 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _154_ (
    .CLK(clk),
    .D(_012_),
    .Q(y_4 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _155_ (
    .CLK(clk),
    .D(_013_),
    .Q(y_5 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _156_ (
    .CLK(clk),
    .D(_014_),
    .Q(y_6 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _157_ (
    .CLK(clk),
    .D(_015_),
    .Q(y_7 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _158_ (
    .CLK(clk),
    .D(_000_),
    .Q(s2_mix_0 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _159_ (
    .CLK(clk),
    .D(_001_),
    .Q(s2_mix_1 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _160_ (
    .CLK(clk),
    .D(_002_),
    .Q(s2_mix_2 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _161_ (
    .CLK(clk),
    .D(_003_),
    .Q(s2_mix_3 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _162_ (
    .CLK(clk),
    .D(_004_),
    .Q(s2_mix_4 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _163_ (
    .CLK(clk),
    .D(_005_),
    .Q(s2_mix_5 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _164_ (
    .CLK(clk),
    .D(_006_),
    .Q(s2_mix_6 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _165_ (
    .CLK(clk),
    .D(_007_),
    .Q(s2_mix_7 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _166_ (
    .CLK(clk),
    .D(_061_),
    .Q(s1_sum_1 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _167_ (
    .CLK(clk),
    .D(_062_),
    .Q(s1_sum_2 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _168_ (
    .CLK(clk),
    .D(_063_),
    .Q(s1_sum_3 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _169_ (
    .CLK(clk),
    .D(_064_),
    .Q(s1_sum_4 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _170_ (
    .CLK(clk),
    .D(_065_),
    .Q(s1_sum_5 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _171_ (
    .CLK(clk),
    .D(_066_),
    .Q(s1_sum_6 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _172_ (
    .CLK(clk),
    .D(_067_),
    .Q(s1_sum_7 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _173_ (
    .CLK(clk),
    .D(_052_),
    .Q(s1_and_0 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _174_ (
    .CLK(clk),
    .D(_068_),
    .Q(s1_and_1 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _175_ (
    .CLK(clk),
    .D(_069_),
    .Q(s1_and_2 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _176_ (
    .CLK(clk),
    .D(_070_),
    .Q(s1_and_3 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _177_ (
    .CLK(clk),
    .D(_071_),
    .Q(s1_and_4 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _178_ (
    .CLK(clk),
    .D(_072_),
    .Q(s1_and_5 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _179_ (
    .CLK(clk),
    .D(_073_),
    .Q(s1_and_6 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _180_ (
    .CLK(clk),
    .D(_074_),
    .Q(s1_and_7 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _181_ (
    .CLK(clk),
    .D(_053_),
    .Q(s1_sum_0 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _182_ (
    .CLK(clk),
    .D(_054_),
    .Q(s1_xor_1 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _183_ (
    .CLK(clk),
    .D(_055_),
    .Q(s1_xor_2 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _184_ (
    .CLK(clk),
    .D(_056_),
    .Q(s1_xor_3 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _185_ (
    .CLK(clk),
    .D(_057_),
    .Q(s1_xor_4 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _186_ (
    .CLK(clk),
    .D(_058_),
    .Q(s1_xor_5 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _187_ (
    .CLK(clk),
    .D(_059_),
    .Q(s1_xor_6 ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _188_ (
    .CLK(clk),
    .D(_060_),
    .Q(s1_xor_7 ),
    .RESET_B(rst_n)
  );
endmodule
