create_clock -name core -period 10 [get_ports clk]
set_clock_transition 0.1 [get_clocks core]
set_input_delay -clock core -max 1 [get_ports {a d}]
set_input_delay -clock core -clock_fall -max 1 [get_ports b]
set_input_transition 0.1 [get_ports {a b d}]
set_input_delay -clock core -min 1 [get_ports a]
set_input_delay -clock core -clock_fall -min 1 [get_ports b]
