create_clock -name core -period 10 [get_ports clk]
set_clock_transition 0.1 [get_clocks core]
set_input_delay -clock core -max 1 [get_ports d]
set_input_delay -clock core -min 1 [get_ports d]
set_input_transition 0.1 [get_ports d]
set_output_delay -clock core -clock_fall -max 2 [get_ports q]
set_output_delay -clock core -clock_fall -min 0 [get_ports q]
set_false_path -rise_to [get_clocks core]
