create_clock -name core -period 10 [get_ports clk]
create_generated_clock -name derived -source [get_ports clk] -divide_by 1 -invert [get_pins u_clk/Y]
set_clock_transition 0.1 [get_clocks core]
set_propagated_clock [get_clocks {core derived}]
set_input_delay -clock core -max 1 [get_ports d]
set_input_delay -clock core -min 1 [get_ports d]
set_input_transition 0.1 [get_ports d]
