create_clock -name core -period 10 [get_ports clk]
set_clock_transition 0.1 [get_clocks core]
set_propagated_clock [get_clocks core]
set_input_delay -clock core -max 1 [get_ports d]
set_input_delay -clock core -min 1 [get_ports d]
set_input_transition 0.1 [get_ports d]
set_ideal_network [get_nets cclk]
set_ideal_latency -rise -min 0.3 [get_nets cclk]
set_ideal_latency -rise -max 0.8 [get_nets cclk]
set_ideal_latency -fall 1.5 [get_nets cclk]
set_ideal_transition -rise 0.2 [get_nets cclk]
set_ideal_transition -fall 0.4 [get_nets cclk]
