create_clock -name core -period 10 [get_ports clk]
set_clock_transition 0.1 [get_clocks core]
set_propagated_clock [get_clocks core]
set_input_delay -clock core -max 1 [get_ports d]
set_input_delay -clock core -min 1 [get_ports d]
set_input_transition 0.1 [get_ports d]
set_clock_latency -source -rise -early 0.2 [get_clocks core]
set_clock_latency -source -rise -late 0.6 [get_clocks core]
set_clock_latency -source -fall -early 1 [get_clocks core]
set_clock_latency -source -fall -late 2 [get_clocks core]
